---
title: "Exploring lakefish data"
author: "Emma Sofie Skarstein and Lyder Iversen"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
library(ggplot2)
library(sf) # for sf objects
library(dplyr) # for smoother dataframe-manipulation
library(here) # for cleaner filepath-handling
library(mapview) # for nice maps
library(ggmap) # also for nice maps
library(maps)
library(maptools)
library(mapdata)
```

First, to download the data, ... 
```{r}
# Include completely minimal script to download data. 
# Considerations: 
#     Which data do we want to look at?
#     Do we want to do any preparation beyond converting to sf-object?

# Load data downloaded in "download.R". Also remove all variables that contain NA-values.
# occ <- readRDS(here::here("data","GBIF_download.rds")) %>% 
#   dplyr::select_if(~!all(is.na(.)))
# 
# lakes <- readRDS(here::here("data","lake_polygons.rds"))
# occ_sf <- occ %>% 
#   st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), crs = 4326) %>%    # Convert to sf object for easier handling. crs = Coordinate Reference System
#   st_transform(st_crs(lakes)$epsg) %>%    # Transform coordinate system
#   dplyr::select(gbifID, occurrenceID, catalogNumber, geometry, species, taxonKey, datasetKey, locality, municipality, county, countryCode, locationID, eventDate, year, month, day, samplingProtocol, eventID, fieldNumber, recordedBy, dynamicProperties, collectionCode, datasetName, license, institutionCode)    
# Select a few of the variables


#source(here::here("GBIF_download","Match_to_lake.R"))
occ_matched <- readRDS(here::here("data","occ_matched.rds"))
lakes <- readRDS(here::here("data","lake_polygons.rds"))

occ_sf <- occ %>% 
  st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), crs = 4326) %>%    # Convert to sf object for easier handling. crs = Coordinate Reference System
  st_transform(st_crs(lakes)$epsg) %>%    # Transform coordinate system
  dplyr::select(gbifID, occurrenceID, catalogNumber, geometry, species, taxonKey, datasetKey, locality, municipality, county, countryCode, locationID, eventDate, year, month, day, samplingProtocol, eventID, fieldNumber, recordedBy, dynamicProperties, collectionCode, datasetName, license, institutionCode)    # Select a few of the variables

source(here::here("GBIF_download","Match_to_lake.R"))
```

Next, some basic plotting.
```{r}
# Using mapview in the rmd-document does work and produces super nice plot, but it takes absolutely for ever to run.
# mapview(occ_sf)

data.coords <- cbind(occ_matched$decimalLongitude, occ_matched$decimalLatitude)
# data.coords <- SpatialPointsDataFrame(coords=cbind("long"=occ_matched$decimalLongitude, "lat"=occ_matched$decimalLatitude))

# Plot presence/absence
norway <- ggplot2::map_data("world", region = "Norway")
ggplot() + geom_map(data = norway, map = norway, aes(long, lat, map_id=region), color="#2b2b2b", fill=NA) + geom_point(aes(x = lakes$decimalLongitude, y = lakes$decimalLatitude), size=0.001, color = "grey") + geom_point(aes(x = occ_matched$decimalLongitude, y = occ_matched$decimalLatitude), size=0.001, color = "red")

```
